### ISSUE TITLE
docker logging size

### ISSUE THREAD

**Issue by mchosc** [greymass/docker-nodeos#1]
in the main docker-compose.yaml file it would be great to add docker container trimming for example:
```
version: '3.6'
services:
    nodeos:
        env_file:
            - .env
        extends:
            file: ./configs/docker/nodeos-minimal-api.yaml
            service: nodeos
        logging:
            driver: "json-file"
            options:
              max-size: "500k"
              max-file: "1024"
    nginx:
        depends_on:
            - nodeos
        extends:
            file: ./configs/docker/nginx.yaml
            service: nginx
        profiles: ["nginx"]
        logging:
            driver: "json-file"
            options:
              max-size: "500k"
              max-file: "1024"
```
